### ISSUE TITLE
Dashboard: Viewing Parties

### ISSUE THREAD

**Issue by b-enji-cmd** [b-enji-cmd/viewing_party#10]
As an authenticated user,
I should see the viewing parties I have been **invited** to with the following details:
- Movie Title, which links to the movie show page
- Date and Time of Event
- who is hosting the event
- list of friends invited, with my name in **bold**

I should also see the viewing parties that I have **created** with the following details:
- Movie Title, which links to the movie show page
- Date and Time of Event
- That I am the host of the party
- List of friends invited to the viewing party

**Comment by Diana20920** [comment]
*The following is committed under branch I created `dashboard_viewing_parties`, but it has not been pushed.*
### Added
- Condition in view `app/views/users/show.html.erb` if the user has not been invited to any parties yet.
- Test for above
- Header for viewing parties section and matching test

**Note**
I have created the test structure for issue #10 but cannot complete it since we need feature to create parties first.

**Comment by Diana20920** [comment]
At this point, we are safe to start a new branch from `main` since there is nothing of substance in this one.
